version: '2'
services:
  mtpoc-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/mtpoc/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mtpoc
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
